name: Post on Approve
on:
  issues:
    types: [labeled]

jobs:
  post:
    name: Post
    runs-on: ubuntu-latest
    if: github.event.label.name == 'approved'
    steps:
    - uses: actions/checkout@v2
    - name: posting
      run: ./.github/workflows/issue_post.sh
    - name: regen site
      uses: nelsonjchen/gh-pages-pelican-action@0.1.5

    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GITHUB_ISSUE: ${{github.event.issue.number}}
